### PR TITLE
fix(genui): add missing `weight` property to `Component` constructor; default `TextField` `width` to 1 when nested in a `Row`

### LINKED ISSUE #559: GenUI TextField crashes with “InputDecorator unbounded width” when generated using A2UI (Flutter GenUI v0.5.1)
Use this system prompt (or any prompt that generates TextFields inside a Row/Column):

Your job is to build UI using ONLY the built-in CoreCatalogItems.

Always generate:
1. A top search bar (TextField + Button)
2. A search results list
3. A chat message list
4. A bottom input area (TextField + Button)

IMPORTANT:
- Wrap every TextField in a width-bounded Box or Expanded.
- Do NOT put TextField directly inside a Row or Column without constraints.
- Do not specify surface IDs manually.
- Always send BeginRendering after updates.

=====================================================================================
Actual Results :

Flutter throws the runtime error:
InputDecorator cannot have an unbounded width.
TextField must be inside a width-bounded parent.

The crash happens even when:

1. Instructions explicitly force width constraints

2. TextFields are wrapped in Containers, Boxes, or Expanded

3. No manual surface IDs are used
 
4. Using only default CoreCatalogItems

=====================================================================================
Expected Results :
GenUI should generate TextField layouts that obey Flutter’s width-bounded constraint:

1. TextField inside Box(width: infinity)

2. TextField inside Expanded

3. TextField inside Container (width constraints)

4. The UI should render without crashing.

=====================================================================================
Sample Code:

import 'package:flutter/material.dart';
import 'package:genui/genui.dart';
import 'package:genui_firebase_ai/genui_firebase_ai.dart';

class Home extends StatefulWidget {
  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late GenUiConversation conversation;
  final _surfaceIds = <String>[];

  @override
  void initState() {
    super.initState();

    final catalog = CoreCatalogItems.asCatalog();

    final generator = FirebaseAiContentGenerator(
      catalog: catalog,
      systemInstruction: "<SYSTEM PROMPT FROM ABOVE>",
    );

    conversation = GenUiConversation(
      genUiManager: GenUiManager(catalog: catalog),
      contentGenerator: generator,
      onSurfaceAdded: (s) => setState(() => _surfaceIds.add(s.surfaceId)),
      onSurfaceDeleted: (s) => setState(() => _surfaceIds.remove(s.surfaceId)),
    );

    generator.a2uiMessageStream.listen((msg) {
      conversation.genUiManager.handleMessage(msg);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: _surfaceIds.map((id) {
          return GenUiSurface(
            host: conversation.host,
            surfaceId: id,
          );
        }).toList(),
      ),
    );
  }
}

### PR DESCRIPTION
**Pull request by andrewkolos**
## Description

Supersedes https://github.com/flutter/genui/pull/588. Fixes #559.

## Changes 
* **fix 1: `SurfaceUpdateTool`** wasn't parsing the value of the `weight` property and passing it to the `Component` constructor for any component it was constructing[^1]. Definition of `weight` property: https://github.com/flutter/genui/blob/061ba8943160894a16ab0ffeaae99b7859e0ac49/packages/genui/lib/src/model/a2ui_schemas.dart#L227-L230. This change fixes this and makes sure the weight value gets plumbed through properly.
  * I will also use this opportunity to say that optional fields should be largely avoided in internal APIs. Optional parameters are very prone to situations like these where code authors forget to pass values when they meant to (or simply never discovered the parameter's existence to begin with). Optional parameters are best reserved for highly flexible user-facing libraries that need to be both very simple to start with but also highly configurable (e.g. components in UI frameworks, such as `Text` in Flutter). Since we are dealing with an internal API here that is not suffering from any significant amount of API bloat, this PR opts to make `weight` parameter required. The only material drawback of making this parameter required is some extra verbosity in test code, which I personally assign very little importance to.
* **(necessary) refactoring:** `buildWeightedChild` no longer has a `required Component? component` parameter and instead has a `required int? weight` parameter. `component` was only being read for the weight value anyway, and this refactoring also lets us "override" the weight of a `component`. Continue reading to see why we need this.
* **(hacky) fix 2:** the builder of the row catalog item now checks the type of each child component. If it sees a `TextField` without a weight, it will assign it a weight of `1`. This will prevent the layout-induced crashes we see in #559. However, I call this hacky because 1) Row has to be explicitly aware of another catalog component and treat it specially and 2) this is essentially a concession that many A2UI layouts are doomed to be laid out in noticeably different ways across different renderers (even if you tweaked the common variables like colors and padding to be the same across each of the renderers). I am okay with making this concession for now, especially that different UI frameworks fundamentally compute constraints in differing ways, making this a high-cost (near intractable?) problem to solve. It also isn't clear to me how many software products will really suffer from the problem to a significant degree (e.g. "we need a piece of generated UI to _look_ identical on both our HTML and native Android apps").

## Screenshots

image

Created using the repro instructions provided by the parent issue. In this scenario, the agent did not provide any weights for any child elements of rows, so this PR's change prevents a crash by assigning a `weight` of `1` to the text fields.

Another example (using simple_chat):

image

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I have added sample code updates to the [changelog].
- [x] I updated/added relevant documentation (doc comments with `///`).

[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md
[changelog]: ../CHANGELOG.md

[^1]: https://github.com/flutter/genui/blob/061ba8943160894a16ab0ffeaae99b7859e0ac49/packages/genui/lib/src/core/ui_tools.dart#L35-L37

### CODE REVIEW

File: packages/genui/lib/src/catalog/core_widgets/row.dart [hunk 1]
```diff
@@ -142,7 +146,11 @@ final row = CatalogItem(
                   DataPath('$dataBinding/$i'),
                 ),
                 buildChild: itemContext.buildChild,
-                component: itemContext.getComponent(componentId),
+                weight:
+                    itemContext.getComponent(componentId)?.weight ??
+                    (itemContext.getComponent(componentId)?.type == 'TextField'
+                        ? 1
+                        : null),
```
[the remark this answers is not in the document]
Comment (andrewkolos) [reply packages/genui/lib/src/catalog/core_widgets/row.dart]: The suggested code is incorrect, but the sentiment here is good. I incorporated it into [avoid re-fetching weight/type when looping over each child](https://github.com/flutter/genui/pull/603/commits/b2ebc54978fed9f5886e0e0f18cdcabdabbce803)

**Comment by jacobsimionato** [comment]
Hey this sounds very good! Can you include a screenshot with some example rendered layouts?

**Comment by andrewkolos** [comment]
> Hey this sounds very good! Can you include a screenshot with some example rendered layouts?

Added some screenshots.

File: packages/genui/lib/src/catalog/core_widgets/row.dart [hunk 2]
```diff
@@ -123,13 +124,21 @@ final row = CatalogItem(
...
+                          : null),
                 ),
               )
               .toList(),
         );
       },
       templateListWidgetBuilder: (context, list, componentId, dataBinding) {
+        final Component? component = itemContext.getComponent(componentId);
+        final int? weight =
+            component?.weight ?? (component?.type == 'TextField' ? 1 : null);
```
Comment (jacobsimionato) [inline packages/genui/lib/src/catalog/core_widgets/row.dart:140]: This LGTM as a practical fix for this now! I think we need a more scalable solution long term, to avoid other leaf components having this issue. We should figure out what circumstances this error happens in - is it for any leaf component that has an unbounded max width or height? Maybe we need them to be identifiable somehow. Either way, this is a great first step I think!

**Review by jacobsimionato — APPROVED** [review]
Nice!

File: packages/genui/lib/src/catalog/core_widgets/row.dart (hunk 2 above)
Comment (andrewkolos) [reply packages/genui/lib/src/catalog/core_widgets/row.dart:140]: Yeah, constraints go down; sizes go up and all that[^1]. Basically any widget that relies on a constraint from their parent to figure out how large they should be. For example, I suspect sliders within rows will fall victim to this exact crash.

[^1]: https://docs.flutter.dev/ui/layout/constraints

Comment (andrewkolos) [reply packages/genui/lib/src/catalog/core_widgets/row.dart:140]: And yeah, the cleaner solution would be some sort of declaration within the catalog that describe what constraint(s) a widget needs to be able to render. We'd also have to do some plumbing and/or refactoring to make this information available to layout widgets like `Row` and `Column`.
