### PR TITLE
fix: consuming v0.9 A2UI JSONL stream

### LINKED ISSUE #867: Fails to consume a v0.9 A2UI JSONL stream
**Describe the bug**
The current version of the SDK fails to consume a v0.9 A2UI JSONL stream.

**To Reproduce**
Add the following test to `packages/genui/test/transport/a2ui_parser_transformer_test.dart` and run it. It fails because the current implementation turns the JSONL newline character (`'\n'`) into a `TextEvent`.

```dart
    test('extracts messages from a JSONL stream', () async {
      final StreamQueue<GenerationEvent> queue = StreamQueue(stream);

      controller.add(
        '{"version": "v0.9", "createSurface": {"surfaceId": "foo", "catalogId": "genui"}}',
      );

      controller.add('\n');

      controller.add(
        '{"version": "v0.9", "createSurface": {"surfaceId": "bar", "catalogId": "genui"}}',
      );

      final firstEvent = (await queue.next) as A2uiMessageEvent;
      expect(firstEvent.message, isA<CreateSurface>());
      expect((firstEvent.message as CreateSurface).surfaceId, 'foo');

      final secondEvent = (await queue.next) as A2uiMessageEvent;
      expect(secondEvent.message, isA<CreateSurface>());
      expect((secondEvent.message as CreateSurface).surfaceId, 'bar');

      await queue.cancel();
    });
```

**Expected behavior**
The SDK extracts and parses the 2 expected `CreateSurface` messages.

**Additional context**
The A2UI v0.9 documentation for transport decoupling [states](https://github.com/google/A2UI/blob/main/specification/v0_9/docs/a2ui_protocol.md#transport-decoupling) (emphasis mine):

> Message framing: The transport must clearly delimit individual JSON envelope messages (e.g., **using newlines in JSONL**, WebSocket frames, or SSE events).

### PR DESCRIPTION
**Pull request by juan-vgv**
# Description

Fixes #867.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [ ] I have added sample code updates to the [changelog].
- [ ] I updated/added relevant documentation (doc comments with `///`).

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md
[changelog]: ../CHANGELOG.md

### CODE REVIEW

**Review by jacobsimionato — APPROVED** [review]
LGTM - thanks for the great bug report and fix!

I'd love @polina-c to take a look too before we merge.

File: packages/genui/lib/src/transport/a2ui_parser_transformer.dart [hunk 1]
```diff
@@ -130,22 +131,30 @@ class _A2uiParserStream {
...
 
       if (firstPotentialStart == -1) {
-        // No potential JSON start. Emit all.
+        // No potential JSON start.
         if (_buffer.isNotEmpty) {
+          if (_lastWasJson && _buffer.trim().isEmpty) {
+            // Whitespace-only after a JSON message: treat as JSONL separator.
+            // Hold in buffer until more data arrives or stream ends.
+            break;
+          }
```
[the remark this answers is not in the document]
Comment (jacobsimionato) [reply packages/genui/lib/src/transport/a2ui_parser_transformer.dart]: Well, the non-JSON content would be interpreted as text, so I think that it's pretty reasonable for an infinite input stream to cause an OOM eventually. We can rely on other parts of the system to fail to prevent infinite input streams.

**Comment by jacobsimionato** [comment]
LGTM - thanks for the great bug report and fix!

I'd love @polina-c to take a look too before we merge.

Please fix the analyser errors also! Sorry you didn't get to see them earlier because the CI doesn't run automatically for you.

File: packages/genui/lib/src/transport/a2ui_parser_transformer.dart [hunk 2]
```diff
@@ -45,6 +45,7 @@ class _A2uiParserStream {
   late final StreamController<GenerationEvent> _controller;
   StreamSubscription<String>? _subscription;
   String _buffer = '';
+  bool _lastWasJson = false;
```
Comment (polina-c) [inline packages/genui/lib/src/transport/a2ui_parser_transformer.dart]: Can you add comment explaining what means true and what means false for this flag?

Comment (juan-vgv) [reply packages/genui/lib/src/transport/a2ui_parser_transformer.dart]: Hey! 

`true` if the last event was an `A2uiMessageEvent`, `false` otherwise. So the parser can tell how to treat whitespace.

Would you prefer something more explicit? Maybe `_wasLastEventA2UI`?

Comment (polina-c) [reply packages/genui/lib/src/transport/a2ui_parser_transformer.dart]: Yes, it is good. Thanks.

One more thing would be nice to clarify: how treating whitespace is different for the two cases.

And, can you add this comment to the code, above the declaration of _lastWasJson?

Comment (juan-vgv) [reply packages/genui/lib/src/transport/a2ui_parser_transformer.dart]: Done. Added the following:

```dart
  // When true, whitespace-only content is treated as a JSONL separator and
  // discarded. When false, it is emitted as a TextEvent.
```

**Review by polina-c — APPROVED** [review]

File: packages/genui/lib/src/transport/a2ui_parser_transformer.dart (hunk 2 above)
Comment (polina-c) [reply packages/genui/lib/src/transport/a2ui_parser_transformer.dart]: Thank you very much for fixing it and for making well-readable. 🙏
